CREATE TABLE DEPARTMENT ( deptno INT PRIMARY KEY, dname VARCHAR(20), location VARCHAR(20) );
CREATE TABLE FACULTY ( facultyid VARCHAR(5) PRIMARY KEY, fname VARCHAR(15) NOT NULL, classroom_no INT, designation VARCHAR(20), deptno INT, sal INT(10), FOREIGN KEY (deptno) REFERENCES DEPARTMENT(deptno) );
CREATE TABLE STUDENT ( studentid INT PRIMARY KEY, sname VARCHAR(15) NOT NULL, birthdate DATE, facultyid VARCHAR(5), city VARCHAR(20), FOREIGN KEY (facultyid) REFERENCES FACULTY(facultyid) );
INSERT INTO DEPARTMENT (deptno, dname, location) VALUES (20, 'COMPUTER', 'Atmiya'), (30, 'ACCOUNTING', 'Virani'), (40, 'OPERATIONS', 'Atmiya'), (50, 'ELECTRIC', 'Atmiya');
INSERT INTO FACULTY (facultyid, fname, classroom_no, designation, deptno, sal) VALUES ('F10', 'SMITH', 101, 'Lecturer', 30, 38000), ('F11', 'ALLEN', 102, 'Programmer', 20, 35000), ('F12', 'WARD', 103, 'Accountant', 20, 32000), ('F13', 'MARTIN', 104, 'Programmer', 30, 30000), ('F14', 'SCOTT', 105, 'Lecturer', 40, 36000);
INSERT INTO STUDENT (studentid, sname, birthdate, facultyid, city) VALUES (1, 'Peter', '1996-04-23', 'F10', 'Newyork'), (2, 'John', '1996-06-22', 'F11', 'Boston'), (3, 'Kevin', '1995-03-25', 'F10', 'Newyork'), (4, 'Ivan', '1995-05-04', 'F14', 'Newyork'), (5, 'King', '1996-02-17', 'F11', 'Boston'), (6, 'Miller', '1994-04-10', 'F12', 'Germany'), (7, 'Clark', '1994-08-15', 'F12', 'Boston'), (8, 'Adams', '1994-02-28', 'F10', 'Germany'), (9, 'Blake', '1995-01-06', 'F14', 'Germany'), (10,'Turner', '1995-06-03', 'F10', 'Boston');
UPDATE FACULTY SET sal = sal + 500 WHERE facultyid = 'F11';
SELECT * FROM STUDENT WHERE sname LIKE 'K%';
SELECT * FROM STUDENT WHERE sname LIKE '%R';
SELECT * FROM STUDENT WHERE sname LIKE '%E%';
SELECT * FROM FACULTY WHERE sal > 32000;
SELECT * FROM FACULTY WHERE sal < 36000 AND designation = 'Programmer';
SELECT * FROM FACULTY WHERE classroom_no IN (102, 103, 105);
SELECT * FROM DEPARTMENT WHERE dname != 'OPERATIONS';
SELECT * FROM DEPARTMENT WHERE deptno BETWEEN 30 AND 50;
SELECT * FROM STUDENT ORDER BY sname ASC;
SELECT * FROM STUDENT ORDER BY sname DESC;
ALTER TABLE STUDENT DROP COLUMN birthdate;
ALTER TABLE FACULTY MODIFY fname VARCHAR(20);
DELETE FROM STUDENT WHERE city = 'Boston';
ALTER TABLE STUDENT RENAME TO Stud;
